spring:
  application:
    name: lms-core-service
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  protocols:
    rest:
      name: rest
      port: 9999
    dubbo:
      name: dubbo
      port: 20880
        
